# Generated by Django 5.0.6 on 2024-06-07 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(choices=[('APPLE', 'Apple'), ('HP', 'HP'), ('SAMSUNG', 'Samsung'), ('HUAWEI', 'Huawei')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('pulgadas', models.FloatField(choices=[(13.0, '13 pulgadas'), (15.0, '15 pulgadas')])),
                ('resolucion', models.IntegerField(choices=[(720, '720p'), (1080, '1080p'), (1440, '1440p'), (2160, '4K')])),
                ('bateria', models.IntegerField(choices=[(2000, '2000 mAh'), (3000, '3000 mAh'), (4000, '4000 mAh'), (5000, '5000 mAh')])),
                ('almacenamiento', models.IntegerField(choices=[('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB')])),
                ('camara', models.CharField(choices=[('12MP', '12 megapíxeles'), ('16MP', '16 megapíxeles'), ('24MP', '24 megapíxeles')], max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('agotado', 'AGOTADO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(choices=[('debito', 'DEBITO'), ('credito', 'CREDITO'), ('transferencia', 'TRANSFERENCIA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('generacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(choices=[('APPLE', 'Apple'), ('HP', 'HP'), ('SAMSUNG', 'Samsung'), ('HUAWEI', 'Huawei')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('pulgadas', models.FloatField(choices=[(13.0, '13 pulgadas'), (15.0, '15 pulgadas')])),
                ('resolucion', models.IntegerField(choices=[(720, '720p'), (1080, '1080p'), (1440, '1440p'), (2160, '4K')])),
                ('memoria_ram', models.IntegerField(choices=[(2, '2 GB'), (4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB')])),
                ('bateria', models.IntegerField(choices=[(2000, '2000 mAh'), (3000, '3000 mAh'), (4000, '4000 mAh'), (5000, '5000 mAh')])),
                ('almacenamiento', models.IntegerField(choices=[('SSD', '128 GB SSD'), ('SSD', '256 GB SSD'), ('SSD', '512 GB SSD'), ('SSD', '1 TB SSD'), ('HDD', '256 GB HDD'), ('HDD', '512 GB HDD'), ('HDD', '1 TB HDD')])),
                ('tarjeta_video', models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('agotado', 'AGOTADO')], max_length=50)),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empireapp.procesador')),
            ],
        ),
    ]
