# Generated by Django 5.0.6 on 2024-06-28 03:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(choices=[('APPLE', 'Apple'), ('HP', 'HP'), ('SAMSUNG', 'Samsung'), ('HUAWEI', 'Huawei')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ncto', models.DateField(default=django.utils.timezone.now)),
                ('direccion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empireapp.producto')),
                ('imagen', models.ImageField(upload_to='celulares')),
                ('pulgadas', models.FloatField(choices=[(13.0, '13 pulgadas'), (15.0, '15 pulgadas')])),
                ('resolucion', models.IntegerField(choices=[(720, '720p'), (1080, '1080p'), (1440, '1440p'), (2160, '4K')])),
                ('bateria', models.IntegerField(choices=[(2000, '2000 mAh'), (3000, '3000 mAh'), (4000, '4000 mAh'), (5000, '5000 mAh')])),
                ('almacenamiento', models.CharField(choices=[('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB')], default='otro', max_length=50)),
                ('camara', models.CharField(choices=[('12MP', '12 megapíxeles'), ('16MP', '16 megapíxeles'), ('24MP', '24 megapíxeles')], max_length=50)),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
            },
            bases=('empireapp.producto',),
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empireapp.producto')),
                ('imagen', models.ImageField(null=True, upload_to='laptops')),
                ('pulgadas', models.FloatField(choices=[(13.0, '13 pulgadas'), (15.0, '15 pulgadas')])),
                ('resolucion', models.IntegerField(choices=[(720, '720p'), (1080, '1080p'), (1440, '1440p'), (2160, '4K')])),
                ('memoria_ram', models.IntegerField(choices=[(2, '2 GB'), (4, '4 GB'), (8, '8 GB'), (16, '16 GB'), (32, '32 GB')])),
                ('bateria', models.IntegerField(choices=[(2000, '2000 mAh'), (3000, '3000 mAh'), (4000, '4000 mAh'), (5000, '5000 mAh')])),
                ('almacenamiento', models.CharField(choices=[('SSD', '128 GB SSD'), ('SSD', '256 GB SSD'), ('SSD', '512 GB SSD'), ('SSD', '1 TB SSD'), ('HDD', '256 GB HDD'), ('HDD', '512 GB HDD'), ('HDD', '1 TB HDD')], default='otro', max_length=50)),
                ('tarjeta_video', models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], max_length=50)),
                ('procesador', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
            },
            bases=('empireapp.producto',),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empireapp.cart')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empireapp.producto')),
            ],
        ),
    ]
