# Generated by Django 5.0.6 on 2024-06-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metodo_pago',
        ),
        migrations.AlterField(
            model_name='laptops',
            name='procesador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='celulares',
            name='almacenamiento',
            field=models.CharField(choices=[('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='almacenamiento',
            field=models.CharField(choices=[('SSD', '128 GB SSD'), ('SSD', '256 GB SSD'), ('SSD', '512 GB SSD'), ('SSD', '1 TB SSD'), ('HDD', '256 GB HDD'), ('HDD', '512 GB HDD'), ('HDD', '1 TB HDD')], default='otro', max_length=50),
        ),
        migrations.DeleteModel(
            name='Procesador',
        ),
    ]
