# Generated by Django 5.0.6 on 2024-06-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'DISPONIBLE'), ('agotado', 'AGOTADO')], default='DISPONIBLE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptops',
            name='tarjeta_video',
            field=models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD'), ('N/A', 'N/A')], max_length=50),
        ),
    ]
