# Generated by Django 5.0.6 on 2024-06-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0002_delete_metodo_pago_alter_laptops_procesador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celulares',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='estado',
        ),
    ]
