# Generated by Django 5.0.6 on 2024-06-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0002_producto_estado_alter_laptops_tarjeta_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'DISPONIBLE'), ('no disponible', 'NO DISPONIBLE')], max_length=50),
        ),
    ]
