# Generated by Django 5.0.6 on 2024-06-28 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0003_alter_cart_id_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='almacenamiento',
            field=models.CharField(choices=[('128 GB SSD', '128 GB SSD'), ('256 GB SSD', '256 GB SSD'), ('512 GB SSD', '512 GB SSD'), ('1 TB SSD', '1 TB SSD'), ('256 GB HDD', '256 GB HDD'), ('512 GB HDD', '512 GB HDD'), ('1 TB HDD', '1 TB HDD')], default='otro', max_length=50),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('sin confirmar', 'SIN CONFIRMAR'), ('en preparacion', 'EN PREPARACION'), ('enviado', 'ENVIADO'), ('entregado', 'ENTREGADO'), ('devuelto', 'DEVUELTO'), ('rechazado', 'RECHAZADO'), ('cancelado', 'CANCELADO')], default='PENDIENTE', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='pedidos', to='empireapp.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
