# Generated by Django 5.0.6 on 2024-06-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0004_carrito_alter_celulares_precio_alter_celulares_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empireapp.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='empireapp.laptops'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('cliente', 'producto')},
        ),
    ]
