# Generated by Django 5.0.6 on 2024-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0005_alter_pedido_estado_alter_pedido_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
