# Generated by Django 5.0.6 on 2024-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0006_remove_cliente_contraseña_cliente_fecha_ncto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celulares',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='celulares'),
        ),
        migrations.AddField(
            model_name='laptops',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='laptops'),
        ),
    ]
