# Generated by Django 5.0.6 on 2024-06-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empireapp', '0009_remove_pedido_productos_pedido_items_alter_pedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
